image: node:lts
pipelines:
  default:
    - step:
        name: build
        caches:
          - apt
        script:
          - apt-get install zip
          - ./build.sh
        artifacts:
          - build/wp-persistent-checkboxes.zip
definitions:
  caches:
    apt: /var/cache/apt/archives
