image: node:lts
pipelines:
  default:
    - step:
        name: build
        caches:
          - apt
        script:
          - apt-get update && apt-get install zip
          - ./build.sh
          - curl -X POST \
              "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" \
              --form files=@"build/wp-persistent-checkboxes.zip"
definitions:
  caches:
    apt: /var/cache/apt/archives
