name: Build Plugin
on: [push]
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1.1.0
      with:
        version: '12.x'
    - run: ./build.sh
    - uses: actions/upload-artifact@v1.0.0
      with:
        name: plugin
        path: build/persistent-checkboxes.zip
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v1.0.0
        with:
          name: plugin
          path: .
      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./persistent-checkboxes.zip
          asset_name: persistent-checkboxes.zip
          asset_content_type: application/zip
